tabWidth: 4
useTabs: false
semi: true
singleQuote: true
trailingComma: 'es5'
bracketSpacing: true
printWidth: 140
endOfLine: 'lf'
htmlWhitespaceSensitivity: 'ignore'
css:
    singleQuote: true
    trailingComma: 'none'
svelteSortOrder: 'scripts-markup-styles'
bracketSameLine: false
jsxBracketSameLine: false
arrowParens: always
